### ISSUE TITLE
PKGBUILD wrong dependency

### ISSUE THREAD

**Issue by drapado** [ros-noetic-arch/ros-noetic-chomp-motion-planner#1]
Current PKGBUILD still has `ros-noetic-moveit-experimental` as dependency. I'm assuming it should be changed to `ros-noetic-moveit`, but not fully sure if only a `ros-notic-moveit-xxxx` subpackage is needed as I have the meta-package installed

**Comment by acxz** [comment]
Can you point to upstream sources? i.e. their package.xml

**Comment by acxz** [comment]
Resolved with [b36d078](https://github.com/ros-noetic-arch/ros-noetic-chomp-motion-planner/commit/b36d07898c24517084aa42b407aa4b6b5b07964a)
